<a href="https://colab.research.google.com/github/IqmanS/ann_regression_cycle_power_plant/blob/main/ann_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.9.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values #Matrix Features (dataset.iloc[:,0:4])
y = dataset.iloc[:,-1].values #Dependent Variable Vector/Array

In [5]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
#X_train : Matrix Features Training Set
#X_test : Matrix Features Test Set
#y_train : Dependent Variable Training Set
#y_test : Dependent Variable Test Set
X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [7]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))

### Adding the second hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))


### Adding the output layer

In [10]:
ann.add(tf.keras.layers.Dense(units = 1))
#for regression Activation Function of output layer is none

## Part 3 - Training the ANN

### Compiling the ANN

In [11]:
ann.compile(optimizer = 'adam',loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [12]:
ann.fit(X_train,y_train,epochs=100,batch_size = 32)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 5162.8130
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 166.8195
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 161.4372
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 155.0144
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 146.8218
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 137.9966
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 128.6761
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 118.5003
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 107.8509
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 97.3058
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 87.1200
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss:

### Predicting the results of the Test set

In [13]:
y_pre = ann.predict(X_test)
np.set_printoptions(precision = 2)
# y_pre.reshape(len(y_pre),1)
# y_test.reshape(len(y_test),1)
print(np.concatenate((y_pre.reshape(len(y_pre),1),
y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[434.57 431.23]
 [463.41 460.01]
 [468.06 461.14]
 ...
 [475.16 473.26]
 [439.78 438.  ]
 [460.29 463.28]]
